defaults: &defaults
  
  COUPON_DURATION_OF_VALIDITY: 30
  COUPON_SIGN_UP: 0
  COUPON_CHECK_OUT: 1
  
  UNIT_CATTY: 0
  UNIT_KG: 1
  UNIT_STAR: 2  
  UNIT_BAO: 3   
  
  PAYMENT_METHOD_ALLPAY_CREDIT: 0
  PAYMENT_METHOD_ALLPAY_ATM: 1
  PAYMENT_METHOD_ALLPAY_CVS: 2    
  PAYMENT_METHOD_ALLPAY_BARCODE: 3     
  PAYMENT_METHOD_ALLPAY_WEBATM: 4
  PAYMENT_METHOD_TCAT_COD: 5  
  
  SHIPPING_RATES: 135
  CASH_FLOW_FEE: 0.03
  COUPON_FEE: 0.04
  ADMINISTRATION_FEE: 0.03    
  SALES_TAX: 0.0075  
  ALLPAY_CVS_FEE: 30
  
  TRANSFER_FEE: 15
        
  ORDER_STATUS_CANCELED: 0   
  ORDER_STATUS_UNCONFIRMED: 1
  ORDER_STATUS_CONFIRMED: 2
  ORDER_STATUS_CALLED_LOGISTICS: 3
  ORDER_STATUS_SHIPPING: 4 
  ORDER_STATUS_DELIVERED: 5     

  ORDER_REVIEW_UNEATABLE: 0
  ORDER_REVIEW_UNAPPEALING: 1
  ORDER_REVIEW_COMMON: 2
  ORDER_REVIEW_TASTY: 3
  ORDER_REVIEW_DELICIOUS: 4      

  ORDER_SHIPMENT_REVIEW_FAST: 3  
  ORDER_SHIPMENT_REVIEW_COMMON: 2  
  ORDER_SHIPMENT_REVIEW_SLOW: 1 
  
  NOTIFICATION_SYSTEM: 0
  NOTIFICATION_PRODUCT: 1
  NOTIFICATION_COMMENT: 2
  NOTIFICATION_PROMOTION: 3
 
  NOTIFICATION_SUB_NONE: 0 
  NOTIFICATION_SUB_NEW_COMMENT: 1
  NOTIFICATION_SUB_NEW_ORDER: 2
  NOTIFICATION_SUB_NEW_SUB_COMMENT: 3      
  NOTIFICATION_SUB_UPDATING_INVOICE: 4      
  NOTIFICATION_SUB_REVIEW: 5      
  NOTIFICATION_SUB_VERIFY: 6      
  
development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults