defaults: &defaults
  
  COUPON_DURATION_OF_VALIDITY: 30
   
  COUPON_SIGN_UP: 0
  COUPON_CHECK_OUT: 1
  
  UNIT_CATTY: 0
  UNIT_KG: 1
  UNIT_STAR: 2  
  
  PAYMENT_METHOD_ALLPAY_CREDIT: 0
  PAYMENT_METHOD_TCAT_COD: 1 
  
  SHIPPING_RATES: 100
  
  ORDER_STATUS_CANCELED: 0   
  ORDER_STATUS_UNCONFIRMED: 1
  ORDER_STATUS_CONFIRMED: 2
  ORDER_STATUS_SHIPPING: 3 
  ORDER_STATUS_DELIVERED: 4  
    
development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults